# Generated by Django 4.2 on 2023-04-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=400),
        ),
    ]
